import { ClipboardList, ArrowUpRight } from 'lucide-react';

const InsightsDisplay = ({ insights }) => {
  if (!insights) return null;

  return (
    <div className="mt-6 bg-white rounded-xl p-8 shadow-lg border-l-4 border-teal-500 animate-fadeIn">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-2xl font-bold text-gray-800 flex items-center">
          <ClipboardList className="w-6 h-6 mr-2 text-teal-500" />
          AI-Generated Insights
        </h2>
        <button className="text-teal-500 hover:text-teal-700 flex items-center">
          Export <ArrowUpRight className="w-4 h-4 ml-1" />
        </button>
      </div>
      
      <div className="p-4 bg-gray-50 rounded-lg">
        <div className="whitespace-pre-line text-gray-700 leading-relaxed">
          {insights}
        </div>
      </div>
      
      <div className="mt-6 pt-4 border-t border-gray-200">
        <p className="text-sm text-gray-500">
          These insights were generated by our AI analysis engine. For more detailed reports, consider our premium plans.
        </p>
      </div>
    </div>
  );
};

export default InsightsDisplay